### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path

### ISSUE THREAD

**Issue by Electroid** [hugmanrique/Slime#6]
When downloading and using `slime-tools` on Mac OS (Java 1.8), the following error always occurs:

```
Saving chunks...
Error serializing data to slime format!
java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /darwin/x86_64/libzstd-jni.dylib or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in you system.
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.github.luben.zstd.util.Native.load(Native.java:73)
	at com.github.luben.zstd.util.Native.load(Native.java:60)
	at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:11)
	at net.hypixel.slime.SlimeSaver.getSlimeBlob(SlimeSaver.java:64)
	at net.hypixel.slime.MainKt.main(Main.kt:97)
```

**Comment by hugmanrique** [comment]
The slime-tools was provided by the Hypixel team and, sadly, it's not open source. It looks like they forgot to include bindings for Mac, I've tested it in Ubuntu 18 (WSL)

**Comment by astei** [comment]
I had this issue with Linux. Their tool only includes Windows natives. The fix is to download the [appropriate bindings for your OS](https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.4.4-3/) and put the appropriate OS directory into Hypixel's JAR.

**Comment by astei** [comment]
[As promised, an open-source Anvil to Slime converter has arrived.](https://github.com/astei/anvil2slime)

**Comment by zhongziyun1993** [comment]
In gradle, could just specify the classifier.
